# Generated by Django 6.0.1 on 2026-01-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sofa', 'Sofa'), ('chair', 'Chair'), ('table', 'Table'), ('cupboard', 'Cupboard')], default='chair', max_length=20),
            preserve_default=False,
        ),
    ]
